name: learn-github-actions
on:
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: crowdin action
        uses: crowdin/github-action@1.0.4
        with:
          upload_translations: true
          download_translations: false
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
