name: dumy workflow
on:
  push:
    branches: [ main ]
    paths:
    - 'locales-json/en.json'

jobs:
  dummy-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

#       - name: Get changed files
#         id: changed-files
#         uses: tj-actions/changed-files@v10
#         with:
#           files: |
#             locales-json/en.json
            
        
      - name: List all modified files
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
          done
